import './globals.css';
import HeaderLayout from './header/layout';
import WantToStayUpdated from './header/components/WantToStayUpdated';




export const metadata = {
  title: 'StartUp Chihuahua',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body>
        <HeaderLayout />

        <main>
          {children}
        </main>
        <WantToStayUpdated />
      </body>
    </html>
  );
}