// RootLayout.tsx
import { LocaleProvider } from '@components/Localization/LocaleContext';
import './globals.css';
import HeaderLayout from './header/layout';
import { Metadata } from 'next';
import { fetchAndProcessNavData } from '@/lib/Navigation/navData';

export const metadata: Metadata = {
  title: 'StartUp Chihuahua',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo2.webp',
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

// Mark RootLayout as an async Server Component
export default async function RootLayout({ children }: RootLayoutProps) {
  const { navLinks, companyLogo } = await fetchAndProcessNavData('/nav/');

  return (
    <html lang="en" className="overflow-y-scroll">
      <head></head>
      <body>
        <LocaleProvider>
          <HeaderLayout navLinks={navLinks} companyLogo={companyLogo} />
          <main>{children}</main>
        </LocaleProvider>
      </body>
    </html>
  );
}
