import './globals.css';
import HeaderLayout from './header/layout';

export const metadata = {
  title: 'StartUp Chihuahua',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <meta charSet='utf-8' />
      <body>
 
        <HeaderLayout />

        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
