import './globals.css';
import HeaderLayout from './header/layout';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'StartUp Chihuahua',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo2.webp',
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <HeaderLayout />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
